### PR TITLE
This will actually save additional fields, but not all. Needs to be e…

### PR DESCRIPTION
**Pull request by kakulukia**
, but not all. Needs to be enhanced for all options to transfer to the client.

### CODE REVIEW

**Comment by kakulukia** [comment]
ping @DAVIDhaker

**Comment by DAVIDhaker** [comment]
Hi. Excuse. I was in hospital. 

1. About stupid error `a=123` - fixed. In hours will publish.
2. About "additional fields, but not all". By security reasons and for obviousity - must be realizsed via overriding of EventAcceptor. In code must be obviously for the developers, how to data processing.

**Comment by DAVIDhaker** [comment]
In **Send additional data to subordinated services** i wrote `Additional fields are not included in the default behavior for security reasons and for clarity of the project code and the code behavior.`

Thanks for the work, but I choose a slightly different way to solve the problem.

**Comment by kakulukia** [comment]
I clearly didn't read that. Sorry.

**Comment by kakulukia** [comment]
I thought about that for 2 more minutes and while your decision is a good one id like to offer a convenient way for the client side: Why not also define expected fields in the settings and thus save everything that was expected to be transferred from the server?

Clearly this only works for user attributes, but that should cover 90% of all use cases and make people happy. Works for me! :D Security and usability: WIN!

**Comment by kakulukia** [comment]
And i hope the reason for being in the hospital is gone now! Good to have you back!

**Comment by DAVIDhaker** [comment]
Hello! Thanks! I already did leave the hospital. Now feel near good. 

About your offer to add setting, who did affect behavior of basic account updation - nice offer. I will think about it in days and will make improvement. Need time to think.

**Pull request closed without merging**
